Repository apoorvaron/Shorty, pull requests merged in 2023-06, with the labels that each got.

#102 feat: readme.md docs changes added youtube tutorial to setup project
  README.md
Labels: gssoc23, level1

#103 Added chatbot and resolve password validation
  assets/css/shorty.css
  assets/js/shorty.js
  assets/user-img/dummy.webp
  index.php
  siteName.php
  tiny.sql
  user/change-password.php
  user/message.php
  user/register.php
Labels: gssoc23, level2

#128 added hover feature
  .htaccess
  env.php
  siteName.php
  user/assets/css/bootstrap.min.css
Labels: gssoc23

#156 Login as Guest
  .DS_Store
  .htaccess
  admin/dBconn/api.php
  env.php
  guest.php
  includes/footer.php
  includes/header.php
  index.php
  siteName.php
  user/login.php
  user/newLink.php
Labels: good first issue, gssoc23, level2, Level3
