Repository apoorvaron/Shorty, pull requests merged in 2023-07, with the labels that each got.

#208 Merge SiteName.php && env.php
  README.md
  env.php
  guest.php
  includes/footer.php
  index.php
  privacy.php
  siteName.php
  user/alreadyOriginal.php
  user/index.php
  user/newLink.php
  user/preview.php
  user/successCopy.php
Labels: gssoc23, level3

#213 [FEATURE] Add gitignore support to prevent updates of specific files from PR to the main repository
  .gitignore
  README.md
  env.php
Labels: gssoc23

#222 Update README.md
  README.md
Labels: gssoc23, level1

#224 doc: adding maintainer name and contacts
  README.md
Labels: gssoc23, level1

#232 feat: add open graph meta to improve social sharing ✨
  includes/seo.php
Labels: gssoc23

#217 AI ChatBot Added
  includes/chatbotsidebar.php
  includes/header.php
Labels: gssoc23

#239 fix: navbar alignment issue 🛠
  assets/css/shorty.css
  includes/header.php
Labels: gssoc23, level2

#244 🛠️ Fix Copy button functionality in user panel
  user/alreadyOriginal.php
  user/index.php
Labels: gssoc23

#252 ✨✅ "Enter" Key Functionality Added! 🎉🚀
  guest.php
Labels: gssoc23

#253 🔧 Fix Cancel Button, Random, and BlockSpecialChar 🛠️
  user/preview.php
Labels: gssoc23

#269 🚀 Dynamic Domain Integration - Replacing Hardcoded URL with env.php ($env_domain) 💻🔧
  includes/seo.php
Labels: gssoc23, level2

#259 Add about us page #44 (mrprayag077)
  about.php
  assets/css/shorty.css
  assets/images/about.png
  faq.php
  includes/header.php
  privacy.php
Labels: gssoc23

#270 🚀 Updated Regex - Resolving Validity Issue 🔧🔗
  includes/footer.php
Labels: gssoc23

#272 🚀 Fixing Fragment Link Saving - Improved Handling 🔧🔗
  includes/footer.php
Labels: gssoc23

#275 🚀 Standardizing Error, Success, and Warning Messages Across All Pages 🔧📝
  guest.php
  includes/footer.php
  user/edit-profile.php
  user/login.php
  user/preview.php
  user/register.php
Labels: gssoc23

#276 animated hovering back to top #273
  assets/css/shorty.css
Labels: gssoc23
