Repository apoorvaron/Shorty, pull requests merged in 2023-08, with the labels that each got.

#285 Addressing Design and Security Issues - Adding Character Limit and Unauthorized Access Handling 🚀🔒
  user/preview.php
Labels: gssoc23, level2

#287 [FIX] : 🥊 Character Limit for 'Link is For' Field(NewLink Page) - Improving Database Performance 🍬💽
  user/newLink.php
  user/preview.php
Labels: gssoc23

#290 Inline validation in login and register form
  user/login.php
  user/register.php
Labels: gssoc23

#301 fix: Added ARIA attributes in Multiple Form Sections
  user/change-password.php
  user/delete-link.php
  user/edit-profile.php
  user/forget-pass.php
Labels: gssoc23

#297 Added reusable code in faq.php
  faq.php
Labels: gssoc23

#295 Add 404 error page #27
  404.php
Labels: gssoc23

#279 feat: revamp custom link form 🪄 ✨
  assets/css/shorty.css
  guest.php
Labels: gssoc23

#304 Security Fix - ID Validation to Prevent Unauthorized Data Access 🛡️🔒
  admin/dBconn/api.php
  user/successDelete.php
Labels: gssoc23, level3

#303 Form field icons
  guest.php
  index.php
  user/assets/css/bootstrap.min.css
  user/change-password.php
  user/login.php
  user/newLink.php
  user/preview.php
  user/register.php
Labels: gssoc23

#312 Console Clear #263
  guest.php
  includes/footer.php
  user/delete-link.php
  user/header.php
  user/index.php
  user/newLink.php
  user/preview.php
  user/successCopy.php
  user/successDelete.php
Labels: gssoc23

#311 Inline Validation in change password.
  user/change-password.php
Labels: gssoc23, level2

#313 UI Fixes
  guest.php
Labels: gssoc23, level3

#314 fix padding & Ui fixes
  guest.php
Labels: gssoc23, level3

#315 fix padding
  user/newLink.php
Labels: gssoc23, level3

#317 Login Page UI fixes
  user/login.php
Labels: level3

#319 Fix custom Name field
  user/newLink.php
Labels: gssoc23, level3

#320 Fix custom Name field
  user/preview.php
Labels: gssoc23, level3

#321 choose file fixes
  user/edit-profile.php
Labels: gssoc23, level3

#316 feat: make custom link form accessible ✨
  assets/css/shorty.css
  guest.php
Labels: gssoc23, level2

#325 Fix formatting in README
  README.md
Labels: gssoc23

#329 fix: Resolved styles.yml File Code Error in GitHub Issue Templates List
  .github/ISSUE_TEMPLATE/styles.yml
Labels: gssoc23, level1

#330 change password icon color changes
  user/change-password.php
Labels: gssoc23

#331 Choose File button on hover on Edit Profile Page changed
  user/edit-profile.php
Labels: gssoc23

#332 icon color on new link page changed
  user/newLink.php
Labels: gssoc23, level3

#334 🔄 Removed Inline & Internal CSS for About Guest FAQ 🔗📂
  about.php
  assets/css/about.css
  assets/css/faq.css
  assets/css/guest.css
  faq.php
  guest.php
Labels: gssoc23

#337 Home icon changed
  user/login.php
Labels: gssoc23, level3

#345 Registration icon color rectified
  user/register.php
Labels: gssoc23, level3

#346 Login Page color rectified
  user/login.php
Labels: gssoc23

#347 Edit Link icon color change
  user/preview.php
Labels: gssoc23, level3

#348 edit link icon color change
  user/preview.php
Labels: gssoc23, level3

#349 border fixes
  user/newLink.php
Labels: gssoc23, level3

#350 border fixes
  user/preview.php
Labels: gssoc23, level3

#351 border size
  user/edit-profile.php
  user/profile.php
Labels: gssoc23, level3

#352 update quote on change password
  user/change-password.php
Labels: gssoc23, level3

#353 update quote on change password
  user/newLink.php
Labels: gssoc23, level3

#354 unneccesary text removed
  user/header.php
Labels: gssoc23, level3

#355 comments add
  user/header.php
Labels: gssoc23, level3

#356 comments add
  user/change-password.php
Labels: gssoc23, level3

#342 fix: Corrected the project name in issue template
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: gssoc23, level1

#338 feat: revamp hover state of social icons on footer 🪄✨
  assets/css/shorty.css
Labels: gssoc23, level1

#335 TransformationRemoved
  assets/css/shorty.css
Labels: gssoc23, level3

#339 Optimize Code Structure: Externalize CSS for 404, Index, Privacy, and successDelete PHP Pages
  404.php
  assets/css/404.css
  assets/css/homePage.css
  assets/css/privacy.css
  assets/css/successDelete.css
  assets/css/sweetAlertButton.css
  index.php
  privacy.php
  user/successDelete.php
Labels: gssoc23, level3

#357 Externalize CSS for successCopy, Register, Profile, and Preview PHP Pages 🎨🔄
  assets/css/preview.css
  assets/css/profile.css
  assets/css/register.css
  assets/css/successCopy.css
  assets/css/sweetAlertButton.css
  user/preview.php
  user/profile.php
  user/register.php
  user/successCopy.php
Labels: gssoc23

#364 Externalizing CSS for newLink, login, user/index, and header PHP Pages 🛠️🎨
  assets/css/index.css
  assets/css/login.css
  assets/css/newLink.css
  user/assets/css/header.css
  user/header.php
  user/index.php
  user/login.php
  user/newLink.php
Labels: gssoc23

#363 Fix About description
  about.php
Labels: gssoc23

#366 Mobile view text fix
  user/assets/css/style.css
  user/header.php
Labels: gssoc23

#370 Resolve Issue #369 and Align the "Make new Link" form.
  README.md
Labels: gssoc23

#360 feat: implement browser bar theme feature for shorty 🪄✨
  includes/seo.php
Labels: gssoc23, level2

#368 Hover Effect Removed
  assets/css/shorty.css
Labels: gssoc23
